# Generated by Django 5.0.2 on 2024-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_enddate_item_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.IntegerField(),
        ),
    ]
