# Generated by Django 5.0.2 on 2024-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_available_stock_alter_item_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.IntegerField(),
        ),
    ]
